/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVerificarPixRouteImport } from './routes/api/public/verificar-pix'
import { Route as ApiPublicSyncpayWebhookRouteImport } from './routes/api/public/syncpay-webhook'
import { Route as ApiPublicCriarPixRouteImport } from './routes/api/public/criar-pix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerificarPixRoute = ApiPublicVerificarPixRouteImport.update({
  id: '/api/public/verificar-pix',
  path: '/api/public/verificar-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncpayWebhookRoute = ApiPublicSyncpayWebhookRouteImport.update({
  id: '/api/public/syncpay-webhook',
  path: '/api/public/syncpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCriarPixRoute = ApiPublicCriarPixRouteImport.update({
  id: '/api/public/criar-pix',
  path: '/api/public/criar-pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/criar-pix': typeof ApiPublicCriarPixRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
  '/api/public/verificar-pix': typeof ApiPublicVerificarPixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/criar-pix': typeof ApiPublicCriarPixRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
  '/api/public/verificar-pix': typeof ApiPublicVerificarPixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/criar-pix': typeof ApiPublicCriarPixRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
  '/api/public/verificar-pix': typeof ApiPublicVerificarPixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/criar-pix'
    | '/api/public/syncpay-webhook'
    | '/api/public/verificar-pix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/criar-pix'
    | '/api/public/syncpay-webhook'
    | '/api/public/verificar-pix'
  id:
    | '__root__'
    | '/'
    | '/api/public/criar-pix'
    | '/api/public/syncpay-webhook'
    | '/api/public/verificar-pix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCriarPixRoute: typeof ApiPublicCriarPixRoute
  ApiPublicSyncpayWebhookRoute: typeof ApiPublicSyncpayWebhookRoute
  ApiPublicVerificarPixRoute: typeof ApiPublicVerificarPixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verificar-pix': {
      id: '/api/public/verificar-pix'
      path: '/api/public/verificar-pix'
      fullPath: '/api/public/verificar-pix'
      preLoaderRoute: typeof ApiPublicVerificarPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/syncpay-webhook': {
      id: '/api/public/syncpay-webhook'
      path: '/api/public/syncpay-webhook'
      fullPath: '/api/public/syncpay-webhook'
      preLoaderRoute: typeof ApiPublicSyncpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/criar-pix': {
      id: '/api/public/criar-pix'
      path: '/api/public/criar-pix'
      fullPath: '/api/public/criar-pix'
      preLoaderRoute: typeof ApiPublicCriarPixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCriarPixRoute: ApiPublicCriarPixRoute,
  ApiPublicSyncpayWebhookRoute: ApiPublicSyncpayWebhookRoute,
  ApiPublicVerificarPixRoute: ApiPublicVerificarPixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
